"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

format = """
[î‚¶](fg:#7aa2f7)\
$os\
[î‚° ](fg:#7aa2f7)\
$direnv\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
[ ](fg:white)\
$fill\
[ ](fg:white)\
[î‚²](fg:#9ece6a)\
$python\
$nodejs\
[î‚´](fg:#9ece6a)\
\n$character\
"""

right_format = """
$cmd_duration
$time
$battery\
"""

[os]
format = "[$symbol]($style)"
style = 'fg:#1a1b26 bg:#7aa2f7'
disabled = false

[os.symbols]
Macos = "ï…¹ " #ãƒªãƒ³ã‚´ã®icon
Ubuntu = "î¯‰ " #Ubuntuã®icon

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = 'fg:#7aa2f7'
read_only = " ó°Œ¾" #éµã®icon
read_only_style = 'fg:#f7768e bg:#1a1b26'
truncation_length = 3
truncation_symbol = "â€¦/"
truncate_to_repo = false

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)' # nf-pl-left_soft_divider
style = 'fg:purple'
symbol = ' ï„“ ï„¦ ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 4
truncation_symbol = ''

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_status]
style = 'fg:#e0af68'
conflicted = '='
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
diverged = 'â‡•'
up_to_date = 'âœ“'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = 'Â»'
deleted = 'âœ˜'
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_metrics]
added_style = 'fg:#9ece6a'
deleted_style = 'fg:red'
format = '[+$added]($added_style)[/](fg:#7aa2f7)[-$deleted]($deleted_style)'
disabled = false

[fill]
symbol = 'â”€'
style = 'blue'

[python]
format = '[ ${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
symbol = 'îœ¼ ' # nf-dev-python
style = 'fg:#1a1b26 bg:#9ece6a'
pyenv_version_name = true

[nodejs]
format = '[ ${symbol}(${version})]($style)'
symbol = 'îœ˜ '
style = 'fg:#1a1b26 bg:#9ece6a'

[direnv]
format = '[î‚¼$symbol$allowedî‚º]($style) '
style = "bold fg:#1a1b26 bg:#cba6f7"
disabled = false

[character]
success_symbol = "[â¯â¯](bold green)"
error_symbol = "[â¯â¯](bold red)"

# right_format
[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[ î‚³ î‚ $duration]($style) " # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
style = 'fg:#73daca'
format = '[ î‚³ ï€— $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = "%Y-%m-%d %H:%M"
utc_time_offset = "+9"

[battery]
format = ' [$symbol$percentage]($style) '

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'

[[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 30
style = 'bold yellow'
discharging_symbol = 'ğŸ’¦ '
